
testSTree: streeClient.c simpleTreeADT.c simpleTreeADT.h
	gcc streeClient.c simpleTreeADT.c ../../src/dataMatrix/dataMatrixADT.c ../../src/sortedMatrix/*.c -o testSTree -std=gnu11

clean: 
	rm testSTree 

