
testSTree: gradientClient.c ../../src/gradientTree/gradientTreeADT.*
	gcc gradientClient.c ../../src/gradientTree/gradientTreeADT.c ../../src/dataMatrix/dataMatrixADT.c ../../src/sortedMatrix/*.c -o testGTree -std=gnu11 -lm

clean: 
	rm testGTree 

